// Code generated by opt; DO NOT EDIT.
// github.com/boecklim/opt

package example

import (
	"io"
	"time"
)

type Option func(i *ExampleStruct)

// With byteReader of type func() io.ByteReader
func WithByteReader(byteReader func() io.ByteReader) Option {
	return func(s *ExampleStruct) {
		s.byteReader = byteReader
	}
}

// With aSlice of type []float64
func WithASlice(aSlice []float64) Option {
	return func(s *ExampleStruct) {
		s.aSlice = aSlice
	}
}

// With aPointer of type *string
func WithAPointer(aPointer *string) Option {
	return func(s *ExampleStruct) {
		s.aPointer = aPointer
	}
}

func New(firstMember string, SecondMember int, timestamp time.Time, opts ...Option) *ExampleStruct {
	newInstance := ExampleStruct{}

	for _, opt := range opts {
		opt(&newInstance)
	}

	return &newInstance
}
